[questions]
q0 = "True + True"
q1 = "True + False"
q2 = "False + True"
q3 = "False + False"

[answers]
q0 = "True"
q1 = "True"
q2 = "True"
q3 = "True"

[options]
q0 = [ "True", "False",]
q1 = [ "True", "False",]
q2 = [ "True", "False",]
q3 = [ "True", "False",]
